// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: raftapi.proto

package raftapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_raftapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_raftapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *PutResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_raftapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         *bool                  `protobuf:"varint,1,opt,name=found" json:"found,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_raftapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil && x.Found != nil {
		return *x.Found
	}
	return false
}

func (x *GetResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type CacheHitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cachehits     *uint64                `protobuf:"varint,1,opt,name=cachehits" json:"cachehits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheHitsResponse) Reset() {
	*x = CacheHitsResponse{}
	mi := &file_raftapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheHitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHitsResponse) ProtoMessage() {}

func (x *CacheHitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHitsResponse.ProtoReflect.Descriptor instead.
func (*CacheHitsResponse) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{4}
}

func (x *CacheHitsResponse) GetCachehits() uint64 {
	if x != nil && x.Cachehits != nil {
		return *x.Cachehits
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_raftapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_raftapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_raftapi_proto_rawDescGZIP(), []int{5}
}

var File_raftapi_proto protoreflect.FileDescriptor

const file_raftapi_proto_rawDesc = "" +
	"\n" +
	"\rraftapi.proto\x12\araftapi\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"5\n" +
	"\vPutResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"1\n" +
	"\x11CacheHitsResponse\x12\x1c\n" +
	"\tcachehits\x18\x01 \x01(\x04R\tcachehits\"\a\n" +
	"\x05Empty2\xe1\x01\n" +
	"\rRaftKVService\x120\n" +
	"\x03Put\x12\x13.raftapi.PutRequest\x1a\x14.raftapi.PutResponse\x120\n" +
	"\x03Get\x12\x13.raftapi.GetRequest\x1a\x14.raftapi.GetResponse\x12:\n" +
	"\fGetCacheHits\x12\x0e.raftapi.Empty\x1a\x1a.raftapi.CacheHitsResponse\x120\n" +
	"\x0eResetCacheHits\x12\x0e.raftapi.Empty\x1a\x0e.raftapi.EmptyB\fZ\n" +
	"../raftapi"

var (
	file_raftapi_proto_rawDescOnce sync.Once
	file_raftapi_proto_rawDescData []byte
)

func file_raftapi_proto_rawDescGZIP() []byte {
	file_raftapi_proto_rawDescOnce.Do(func() {
		file_raftapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftapi_proto_rawDesc), len(file_raftapi_proto_rawDesc)))
	})
	return file_raftapi_proto_rawDescData
}

var file_raftapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_raftapi_proto_goTypes = []any{
	(*PutRequest)(nil),        // 0: raftapi.PutRequest
	(*PutResponse)(nil),       // 1: raftapi.PutResponse
	(*GetRequest)(nil),        // 2: raftapi.GetRequest
	(*GetResponse)(nil),       // 3: raftapi.GetResponse
	(*CacheHitsResponse)(nil), // 4: raftapi.CacheHitsResponse
	(*Empty)(nil),             // 5: raftapi.Empty
}
var file_raftapi_proto_depIdxs = []int32{
	0, // 0: raftapi.RaftKVService.Put:input_type -> raftapi.PutRequest
	2, // 1: raftapi.RaftKVService.Get:input_type -> raftapi.GetRequest
	5, // 2: raftapi.RaftKVService.GetCacheHits:input_type -> raftapi.Empty
	5, // 3: raftapi.RaftKVService.ResetCacheHits:input_type -> raftapi.Empty
	1, // 4: raftapi.RaftKVService.Put:output_type -> raftapi.PutResponse
	3, // 5: raftapi.RaftKVService.Get:output_type -> raftapi.GetResponse
	4, // 6: raftapi.RaftKVService.GetCacheHits:output_type -> raftapi.CacheHitsResponse
	5, // 7: raftapi.RaftKVService.ResetCacheHits:output_type -> raftapi.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raftapi_proto_init() }
func file_raftapi_proto_init() {
	if File_raftapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftapi_proto_rawDesc), len(file_raftapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raftapi_proto_goTypes,
		DependencyIndexes: file_raftapi_proto_depIdxs,
		MessageInfos:      file_raftapi_proto_msgTypes,
	}.Build()
	File_raftapi_proto = out.File
	file_raftapi_proto_goTypes = nil
	file_raftapi_proto_depIdxs = nil
}
